image: bernardolins/gtest
git:
  path: github.com/frila/bauer
script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/bauer/lib
  - make deploy
  - cd test
  - make clean
  - make test-all
  - bin/test-all